// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb4zWT_cyFRAWLmNKQPhdxy56gHfT_G2k',
    appId: '1:332657584889:web:b6b5d40aa3cc5e36359028',
    messagingSenderId: '332657584889',
    projectId: 'visionary-voices',
    authDomain: 'visionary-voices.firebaseapp.com',
    storageBucket: 'visionary-voices.appspot.com',
    measurementId: 'G-KKMW0LMC81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3pRQ7unjaeMaYTHc_Wi1OBJooOXLwS3s',
    appId: '1:332657584889:android:f77c9150a44fc6cd359028',
    messagingSenderId: '332657584889',
    projectId: 'visionary-voices',
    storageBucket: 'visionary-voices.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw2U4VxKdxOdN4eLGrBq1hoWcAT6R-6o0',
    appId: '1:332657584889:ios:77ef10fff534e602359028',
    messagingSenderId: '332657584889',
    projectId: 'visionary-voices',
    storageBucket: 'visionary-voices.appspot.com',
    iosBundleId: 'com.example.visionaryVoices',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCw2U4VxKdxOdN4eLGrBq1hoWcAT6R-6o0',
    appId: '1:332657584889:ios:8aa5ce0641affb8c359028',
    messagingSenderId: '332657584889',
    projectId: 'visionary-voices',
    storageBucket: 'visionary-voices.appspot.com',
    iosBundleId: 'com.example.visionaryVoices.RunnerTests',
  );
}
